# filename -- frontend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: java-project-frontend 
spec:
  type: NodePort
  selector:
    app: java-project-frontend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30010